apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operationsConsole.namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.diagnosticsRunner.namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.busybox.namespace }}
